## The makeCache Matrix and cacheSolve functions create a
## cache for the ionverse of a given matrix and a means of
## retrieving the inverted matrix value

## This functions takes an invertible matrix and caches the 
## value of its inverse

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinv <- function(solve) inv <<- solve
    getinv <- function() inv
    list(set = set, get = get,
         setinv = setinv,
         getinv = getinv)
}


## This function returns the value of the inverted
## matrix; this value is obtained for the cache
## generated by the makeCacheMatrix function for
## the given matrix

cacheSolve <- function(x, ...) {
    inv <- x$getinv()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinv(inv)
    inv
}
